- hosts: localhost
  gather_facts: no
  tasks:
    - name: GET CALL
      uri:
        url: https://reqres.in/api/users/2
        method: GET
        return_content: yes
      register: get_result

    - debug:
        msg: "{{ get_result }}"

    - name: get email and fname
      debug:
        msg:
          - "EMAIL : {{ get_result['json']['data']['email'] }}" # one syntax
          - "First Name : {{ get_result.json.data.first_name }}" # 2nd syntax

    - name: POST call
      uri:
        url: https://reqres.in/api/users
        method: POST
        body_format: json
        body:
          name: RAM
          job: DevOps Eng 
        status_code: 201
      register: post_result

    - debug:
        msg: "{{ post_result }}"